version: "2"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka_1:
    image: wurstmeister/kafka:2.11-1.1.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_ADVERTISED_HOST_NAME: kafka_1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
    depends_on:
      - zookeeper
    volumes:
      - ./docker.sock:/var/run/docker.sock
      - ./kafka_1:/kafka
  kafka_2:
    image: wurstmeister/kafka:2.11-1.1.1
    ports:
      - "9093:9092"
    environment:
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_ADVERTISED_HOST_NAME: kafka_2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 2
    depends_on:
      - kafka_1
    volumes:
      - ./docker.sock:/var/run/docker.sock
      - ./kafka_2:/kafka
  kafka_3:
    image: wurstmeister/kafka:2.11-1.1.1
    ports:
      - "9094:9092"
    environment:
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_ADVERTISED_HOST_NAME: kafka_3
      KAFKA_CREATE_TOPICS: "test_topic:2:2,price_subscriptions:2:2,prices:2:2,virtual_price_subscriptions:2:2,virtual_prices:2:2,instrument_info:2:2,instrument_update_info:2:2,pubSub_sync_data:1:1,pubSub_sync_data_requests:2:2,admin_events:1:2,webserver_events:1:2,heartbeats:1:2,registrations:1:2,admin_queries:1:2"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 3
    depends_on:
      - kafka_2
    volumes:
      - ./docker.sock:/var/run/docker.sock
      - ./kafka_3:/kafka
  mkt_gateway_1:
    build: ./images/ubuntu_all_packages
    volumes:
      - .:/usr/src
    working_dir: /usr/src
    depends_on:
      - kafka_3
    command: bash -c "sleep 20 && python3 ./marketConnectivity/PriceFetcher.py kafka_1:9092,kafka_2:9092,kafka_3:9092 MarketGateway_1 DEBUG"
  mkt_gateway_2:
    build: ./images/ubuntu_all_packages
    volumes:
      - .:/usr/src
    working_dir: /usr/src
    depends_on:
      - kafka_3
    command: bash -c "sleep 20 && python3 ./marketConnectivity/PriceFetcher.py kafka_1:9092,kafka_2:9092,kafka_3:9092 MarketGateway_2 DEBUG"
  node_package_installer:
    build: ./images/ubuntu_all_packages
    volumes:
      - .:/usr/src
    working_dir: /usr/src
    command: bash -c "npm i"
  web_server:
    build: ./images/ubuntu_all_packages
    volumes:
      - .:/usr/src
    working_dir: /usr/src
    depends_on:
      - kafka_3
    command: bash -c "sleep 20 && node ./httpWebServer/main.js kafka_3:9092 80 web_server"
    ports:
      - "80:80"
  web_authenticator:
    build: ./images/ubuntu_all_packages
    volumes:
      - .:/usr/src
    working_dir: /usr/src
    depends_on:
      - web_server
      - kafka_3
    #command: node ./httpWebServer/main.js kafka_3:9092 80 WebServer
    command: bash -c "sleep 30 && node ./httpWebServer/WebAuthenticator.js kafka_3:9092 90 web_authenticator DEBUG"
    ports:
      - "90:90"
  data_dispatcher:
    build: ./images/ubuntu_all_packages
    volumes:
      - .:/usr/src
    working_dir: /usr/src
    depends_on:
      - kafka_3
    command: bash -c "sleep 20 && python3 ./DataDispatcher/DataDispatcher.py kafka_3:9092 PriceDispatcher prices,virtual_prices"
  virtual_price_fetcher_1:
    build: ./images/ubuntu_all_packages
    volumes:
      - .:/usr/src
    working_dir: /usr/src
    depends_on:
      - kafka_3
    command: bash -c "sleep 20 && python3 ./VirtualPriceFetcher/VirtualPriceFetcher.py kafka_1:9092,kafka_2:9092,kafka_3:9092 Vpf_1 DEBUG"
  virtual_price_fetcher_2:
    build: ./images/ubuntu_all_packages
    volumes:
      - .:/usr/src
    working_dir: /usr/src
    depends_on:
      - kafka_3
    command: bash -c "sleep 20 && python3 ./VirtualPriceFetcher/VirtualPriceFetcher.py kafka_1:9092,kafka_2:9092,kafka_3:9092 Vpf_2 DEBUG"
  price_dispatcher:
    build: ./images/ubuntu_all_packages
    volumes:
      - .:/usr/src
    working_dir: /usr/src
    depends_on:
      - kafka_3
    command: bash -c "sleep 20 && python3 ./DataDispatcher/DataDispatcher.py kafka_3:9092 PriceDispatcher prices,virtual_prices"
  topic_data_dumper:
    build: ./images/ubuntu_all_packages
    volumes:
      - .:/usr/src
    working_dir: /usr/src
    depends_on:
      - kafka_3
    command: bash -c "sleep 30 && python3 ./testFiles/DataDumper.py kafka_3:9092 DataDumper admin_queries,web_authenticator,admin_events,registrations INFO"
  sync_data_provider:
    build: ./images/ubuntu_all_packages
    volumes:
      - .:/usr/src
    working_dir: /usr/src
    depends_on:
      - kafka_3
    command: bash -c "sleep 20 && python3 ./SyncDataProvider/SyncDataProvider.py kafka_3:9092 SyncDataProvider DEBUG"
  admin_data_provider:
    build: ./images/ubuntu_all_packages
    volumes:
      - .:/usr/src
    working_dir: /usr/src
    depends_on:
      - kafka_3
    command: bash -c "sleep 10 && python3 ./AdminDataProvider/AdminDataProvider.py kafka_1:9092,kafka_2:9092,kafka_3:9092 admin_data_provider DEBUG"

