version: '2.1'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.11-1.1.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 169.254.35.10
      KAFKA_CREATE_TOPICS: "test_topic:1:1,price_subscriptions:1:1,market_price_subscriptions:1:1,prices:1:1,virtual_price_subscriptions:1:1,virtual_price_calculations:1:1,virtual_prices:1:1,instrument_info:1:1,instrument_update_info:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
    links:
      - zookeeper
    depends_on:
      - zookeeper
    volumes:
      - ./docker.sock:/var/run/docker.sock
      - ./kafka:/kafka
  mkt_gateway:
    image: python_base
    volumes:
      - .:/usr/src
    working_dir: /usr/src
    links:
      - kafka
    depends_on:
      - kafka
    command: bash -c "sleep 10 && python3 ./marketConnectivity/per_algo_scripts/PriceFetcher.py kafka:9092 MarketGateway DEBUG"
  WebServer:
    image: node:16.16-alpine3.15
    volumes:
      - ..:/usr/src
    working_dir: /usr/src
    links:
      - kafka
    depends_on:
      - mkt_gateway
    command: node ./httpWebServer/main.js kafka:9092 80 WebServer
    ports:
      - "80:80"
  price_dispatcher:
    image: python_base
    volumes:
      - .:/usr/src
    working_dir: /usr/src
    links:
      - kafka
    depends_on:
      - WebServer
    command: bash -c "sleep 10 && python3 ./microServices/priceDispatcher.py kafka:9092 PriceDispatcher"
  virtual_price_fetcher:
    image: python_base
    volumes:
      - .:/usr/src
    working_dir: /usr/src
    links:
      - kafka
    depends_on:
      - kafka
    command: bash -c "sleep 10 && python3 ./marketConnectivity/VirtualPriceFetcher.py kafka:9092 VirtualPriceFetcher DEBUG"
  virtual_price_dispatcher:
    image: python_base
    volumes:
      - .:/usr/src
    working_dir: /usr/src
    links:
      - kafka
    depends_on:
      - WebServer
    command: bash -c "sleep 10 && python3 ./microServices/VirtualPriceDispatcher.py kafka:9092 VirtualPriceDispatcher DEBUG"
  
