version: '2.1'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.11-1.1.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 169.254.35.10
      KAFKA_CREATE_TOPICS: "test_topic:1:1,price_subscriptions:1:1,prices:1:1,virtual_price_subscriptions:1:1,virtual_prices:1:1,instrument_info:1:1,instrument_update_info:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
    links:
      - zookeeper
    depends_on:
      - zookeeper
    volumes:
      - ./docker.sock:/var/run/docker.sock
      - ./kafka:/kafka
  mkt_gateway:
    image: market_gateway
    volumes:
      - .:/usr/src
    working_dir: /usr/src
    links:
      - kafka
    depends_on:
      - kafka
    command: python3 ./marketConnectivity/per_algo_scripts/PriceFetcher.py kafka:9092