FROM ubuntu
RUN apt-get update
# && apt-get upgrade
RUN apt-get install -y software-properties-common
RUN apt-get install -y openjdk-8-jdk
RUN apt-get install -y openjdk-8-jre
RUN apt-get install -y wget
RUN apt-get install -y vim 
RUN apt-get install -y cmake gcc g++
RUN apt-get install -y build-essential 
RUN apt-get install -y git 
RUN apt-get install -y gdb
RUN apt-get install -y python
RUN apt-get install -y python3-pip
RUN pip install python-binance
RUN pip install --upgrade poloniexapi
RUN pip install aiokafka
RUN pip install pudb 

